[package]
name = "fase-cli"
version = "0.1.0"
description = "package builder and manager"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
clap = { workspace = true }
compio = { workspace = true }
cyper = { workspace = true, features = ["stream"] }
fase-api = { workspace = true }
fase-runtime = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_yml = { workspace = true }
url = { workspace = true }
