apiVersion: v1alpha1
kind: Build
labels:
  fooname: bar
steps:
  - id: fetch
    act:
      name: fetch-http
    with:
      url: https://github.com
  - id: archive
    needs:
      - fetch
    act:
      name: archive-zstd
