apiVersion: fase.io/v1alpha1
kind: RequestGenerator
metadata: {name: hello-nightly}
spec:
  schedule:
    cron: "0 2 * * *"
  template:
    request:
      artifactSelector:
        matchLabels:
          name: hello-package
          version: "{{ source.kernelVersion }}"
          arch: "{{ matrix.arch }}"
      variables:
        version: "{{ source.kernelVersion }}"
        arch: "{{ matrix.arch }}"
  matrix:
    arch: [amd64, arm64]
  source:
    type: kernel-release
    selector: {latest: true}
