[package]
name = "fase-runtime"
version = "0.1.0"
description = "runtime execution support for fase resources"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
compio = { workspace = true }
cyper = { workspace = true }
fase-api = { workspace = true }
futures = { workspace = true }
url = { workspace = true }
zstd = { workspace = true }
