apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-glibc-pandas
spec:
  rerun: 3
  artifactSelector:
    matchLabels:
      name: pandas-glibc-wheels
      version: "3.0.6"
      source-deps: fase-openblas
---
apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-glibc-ml-dtypes
spec:
  rerun: 2
  artifactSelector:
    matchLabels:
      name: ml-dtypes-glibc-wheels
      version: "0.6.0"
      source-deps: fase-openblas
