apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - jax.yaml
  - glibc.yaml
  - probabilistic.yaml
  - rocm.yaml
  - numba.yaml
  - pure.yaml
  - glibc_extra.yaml
  - glibc_python.yaml
  - verify.yaml
  - requests.yaml
  - pure_requests.yaml
