apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-musl-scipy
spec:
  artifactSelector:
    matchLabels:
      name: scipy
      version: "1.18.1"
      recipe: scipy-build-v1
---
apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-glibc-pymc
spec:
  artifactSelector:
    matchLabels:
      name: pymc-glibc-wheels
      version: "6.3.2"
---
apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-rocm-sdk-gfx942
spec:
  rerun: 1
  artifactSelector:
    matchLabels:
      name: rocm-gfx942-sdk
      version: "7.14.1"
      gpu: gfx942
---
apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-glibc-python
spec:
  artifactSelector:
    matchLabels:
      name: python-glibc
      version: "3.13.15"
---
apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-pure-cachetools
spec:
  artifactSelector:
    matchLabels:
      name: cachetools-glibc-wheels
      version: "6.2.6"
---
apiVersion: skyw.top/v1beta1
kind: Request
metadata:
  name: champion-pure-arviz
spec:
  artifactSelector:
    matchLabels:
      name: arviz-glibc-wheels
      version: "1.3.0"
