name: Test and publish images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: fase-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    container: rust:1.98-bookworm
    steps:
      - uses: actions/checkout@v7.0.1
      - run: cargo test --locked --workspace

  controller:
    if: github.event_name == 'push'
    needs: test
    permissions:
      contents: read
      packages: write
    uses: adamanteye/actions/.github/workflows/docker.yml@91cda50cf0bb4e5fc733e638f3b5c96ae2303b97
    with:
      name: fase
      owner: skyworks-neo
      path: .
      platforms: linux/amd64
      rotate: false

  helper:
    if: github.event_name == 'push'
    needs: controller
    permissions:
      contents: read
      packages: write
    uses: adamanteye/actions/.github/workflows/docker.yml@91cda50cf0bb4e5fc733e638f3b5c96ae2303b97
    with:
      name: fase-helper
      owner: skyworks-neo
      path: ./fase-helper
      platforms: linux/amd64
      rotate: false
